### ISSUE TITLE
Apple Silicon Support

### ISSUE THREAD

**Issue by jbremz** [marcoppasini/musika#13]
Hey - this is great! ☺️ 

I believe some of the requirements (e.g. numpy==1.20.3 and tensorflow) mean that this isn't compatible with Apple Silicon (at least on my M1 Pro)?

Still playing around with the installation to see if I can get it working 🙂

**Comment by marcoppasini** [comment]
Take a look at this discussion: https://github.com/marcoppasini/musika/discussions/8

Hope this helps!

**Comment by jbremz** [comment]
@marcoppasini this sorted it thanks!
