### ISSUE TITLE
Uploading model weights to their own repo on Hugging Face

### ISSUE THREAD

**Issue by NimaBoscarino** [marcoppasini/musika#2]
Hello! Since you're already planning on publishing the Musika code here on GitHub, this could also be an opportunity to publish the models themselves as [model repos](https://huggingface.co/docs/hub/models-uploading) on Hugging Face. Right now I see that the models are embedded within the Spaces repo, but this way once your code is published users would be able to discover and work with your pre-trained models more easily 😄

Happy to help out with this, so let me know!

**Comment by marcoppasini** [comment]
Thank you for letting me know!
I will try to do that once I release all the models and code
