### ISSUE TITLE
Musika for short samples?

### ISSUE THREAD

**Issue by jagilley** [marcoppasini/musika#20]
Hi Marco,

Amazing work here! The finetuning Colab says there's a 50 second minimum length of input samples for finetuing - why is this, and could this be changed with further work? I'd like to generate short snippets of single instruments for use in my music, so I'm curious if Musika can be used for this.

Thank you!

**Comment by marcoppasini** [comment]
Unfortunately Musika is trained on quite long samples by design, so that it can generate music that stays coherent over long time spans.
If you are looking to generate second-long samples, unfortunately the current version of Musika is not the best option!

**Comment by jagilley** [comment]
Got it, thank you!
