### ISSUE TITLE
"Found 0 total samples" error

### ISSUE THREAD

**Issue by cbmtrx** [marcoppasini/musika#21]
Zero samples found so it throws this error:

```
raise errors.InvalidArgumentError(
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected 'tf.Tensor(False, shape=(), dtype=bool)' to be true. Summarized data: b'No files matched pattern: /content/MUSIKA/output/*.npy'
```

I seem to encounter an issue with Google Drive files when using some Colabs. I've seen variations like
/content/[myfolder]
/content/drive/[myfolder]
/content/My Drive/[myfolder]

Maybe it's different for users who aren't on the free 15Gb Drive plan? (I'm paying for 2Tb) Don't know if that's the issue.

Am i missing something? I figured this could just run on a folder of mp3s.

**Addendum: tried converting all files to 44.1 as I noticed that was the format of the demos. No change. Can the Colab not read mp3 files?

**Comment by cbmtrx** [comment]
Yup, can't get it working no matter what I try. Converted all files to 44.1 WAVS, left everything as default, no change.

I see many of these errors before the fintetuning block:

```
Exception ignored! Continuing...
Decoding failed. ffmpeg returned error code: 1
```

Dying to try this.

**Comment by marcoppasini** [comment]
It seems like you are specifying an empty path for your mp3 files! You can check the position of your folder by navigating to it in the "File" tab in colab (the little folder icon on the left).

**Comment by cbmtrx** [comment]
Got it going, thanks! So this is what has me so puzzled: the Colab defaults to /content/[myfoldername] but I only got it working by replacing all instances with /content/**drive/MyDrive**/[myfoldername].

Are others able to run the Colab with the Drive location defaults?

**Comment by cbmtrx** [comment]
OK so I'm def getting weird behavior on this. I've now tried a dozen times today and it consistently finds 0 samples. Tried WAV and mp3, all at 44.1/16. The audio is over 6 mins. I'm using the correct folder (checked it, rechecked it in the File tab).

Did something change in the last few days?

**Comment by marcoppasini** [comment]
Very weird, I did not change anything
Can you check if it works with another audio file?

**Comment by cbmtrx** [comment]
Ah...I converted the mono WAV into stereo...problem solved. Must have missed the memo on mono files! Tx
