### ISSUE TITLE
NaN loss

### ISSUE THREAD

**Issue by cyrusasfa** [marcoppasini/musika#22]
Hello :) 

After 18 epochs, some losses hit `nan`

```
Epoch 41/250: 100%|████████████████| 9375/9375 [07:11<00:00, 21.73it/s, DR=713, DF=nan, G=nan, GP=2.16e+4, LR=0.0001, TIME=0.0615]
```

I am unsure where the issue could be. Is this expected behaviour?

**Comment by marcoppasini** [comment]
Unfortunately it happens sometimes when training GANs! You can restart training from the last healthy checkpoint specifying it with --load_path
