### ISSUE TITLE
Musica Encode : Error: ConcatOp : Ranks of all input tensors should match 

### ISSUE THREAD

**Issue by trholding** [marcoppasini/musika#24]
Hi Marco, I am getting the following error. Do you have any hints to fix this?
```
$ python musika_encode.py --files_path ./WAV --save_path ./ENC --whole True


Using CPU...

Checking if models are already available...
Models are available!
/home/skunkwork/.local/lib/python3.10/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer HeUniform is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
Encoders/Decoders loaded from checkpoints/ae
Networks initialized
  0%|                                                                                    | 0/1 [00:00<?, ?it/s]{{function_node __wrapped__ConcatV2_N_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} ConcatOp : Ranks of all input tensors should match: shape[0] = [94998808] vs. shape[1] = [3608,2] [Op:ConcatV2] name: concat
Exception ignored! Continuing...
100%|████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.82s/it]
```

**Comment by marcoppasini** [comment]
It seems like you have only one file in the WAV path, correct? 
Which format is it? And is it stereo?

**Comment by trholding** [comment]
> It seems like you have only one file in the WAV path, correct? Which format is it? And is it stereo?

Thanks for the quick response:

WAV/elon.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, mono 48000 Hz

**Comment by marcoppasini** [comment]
Thanks! You can convert your sample to stereo (duplicating the mono channel) and then try again.
Musika only works with stereo audio unfortunately, at least for now!

**Comment by trholding** [comment]
Ha ha thanks... Can I ask you an unrelated question?

I came to musika because of this:

https://twitter.com/marco_ppasini/status/1583161010122543105

I was wondering the auto encoder outputs 12 hz data. How many bits is that. I am interested cos I am thinking of a very low bit rate codec. Do you think training musika on speech and using the encoder will result in good quality very low bitrate speech (when decoded)?

**Comment by trholding** [comment]
Thank you, worked well.
