### ISSUE TITLE
Incompatible weight shape while starting from model's checkpoint.

### ISSUE THREAD

**Issue by ghost** [marcoppasini/musika#30]
After 2 days of training the model I've stopped the process because of the NaNs in the GF/G metircs. 

When I'm trying to run from checkpoints the following error appears:

`ValueError: Optimizer weight shape (1, 4, 128, 1536) not compatible with provided weight shape (1, 4, 128, 768).` 

I've tried to look at optimizer but it is seem to be ok. My main stack is PyTorch and idk what is wrong with TF...

Could you please give some hints?

P.S. Don't you mind if I rewrite the project to PyTorch and make commitment to your project?

Thanks.

**Comment by marcoppasini** [comment]
Sorry to hear that! When you experience NaNs I recommend you load the last "healthy" checkpoint.
Are you experiencing this error when you load any checkpoint or only the Nan ones?

And regarding rewriting Musika to Pytorch please go for it! I also would like to do it some time this year, but it would be cool and super appreciated if you can give it a shot

**Comment by ghost** [comment]
Thanks for the hints. But the problem was in code logic when I'm trying to resume the training process, files of encoder and decoder were missing because of commented code:

![image](https://user-images.githubusercontent.com/43601384/213782774-9d88ccfe-9e3a-45c7-9665-be15780bb399.png)

And I've tried manually to refactor but it is was hard to be honest :) 

So, now all encoder/decoder weights are also in checkpoint's folder and the training from checkpoint starts smoothly. 

P.S. Ok, no problem I'll commit PyTorch variant. Already started to refactor. As it will be ready I will push changes. Thanks for you work. This model has potential imho. Good luck 👍
