### ISSUE TITLE
Having trouble with installing the requirements

### ISSUE THREAD

**Issue by woolstee** [marcoppasini/musika#31]
I'm pasting the "pip install -r requirements.txt" line of code into the conda command prompt, also within the musika environment, but it keeps giving me this error

**_ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'_**

The text file is in my system because I cloned the repo, as instructed.

I'm really confused. I'm new to all this coding stuff so me being dumb could be the issue lol. Any help?

**Comment by woolstee** [comment]
Also I feel like I should mention that I cloned the repo through GitHub desktop, dunno if that matters or not lol

**Comment by marcoppasini** [comment]
It seems like you cloned the repo in a different directory! If you follow the installation steps carefully, including cloning the repo from the command line, you should be able to install Musika correctly.

You can also try to find the location of the repo you cloned and then open a terminal in that path to install the requirements/execute Musika commands!
