### ISSUE TITLE
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (121,) + inhomogeneous part.

### ISSUE THREAD

**Issue by KomiyamaKatsuya** [marcoppasini/musika#35]
Hi, @marcoppasini. Thank you for your work.
I have the following problem.

I was able to encode an MP4 file and have it learn with that file, but it seems that it is not working because of the error.
```
Traceback (most recent call last):
  File "C:\Users\owner\musika\musika_train.py", line 31, in <module>
    T.train(ds, models_ls)
  File "C:\Users\owner\musika\train.py", line 232, in train
    self.U.save_end(
  File "C:\Users\owner\musika\utils.py", line 434, in save_end
    np.save(path + "/opt_dec.npy", opt_dec.get_weights())
  File "<__array_function__ internals>", line 200, in save
  File "C:\Users\owner\miniconda3\envs\musika\lib\site-packages\numpy\lib\npyio.py", line 521, in save
    arr = np.asanyarray(arr)
`ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (121,) + inhomogeneous part.`
```
Do you know the solution for this error?

**Comment by marcoppasini** [comment]
Did you install the requirements via "requirements.txt" as explained in the README? Specifically, are you using tensorflow 2.10?

**Comment by KomiyamaKatsuya** [comment]
Thank you for your comment!
I install tensorflow 2.10 but I intstalled tensorflow-intel 2.12.
Maybe this is why it didn't work.

I have installed tensorflow-intel 2.10 and resumed learning.
The calculations have not finished yet, but this time it seems to be working!

I will continue to use musika! Thak you for your work!

**Comment by marcoppasini** [comment]
Great, hopefully that was the issue. 
Good luck and thank you for trying out Musika!
