### ISSUE TITLE
installing gradio

### ISSUE THREAD

**Issue by dr-zaib** [marcoppasini/musika#38]
hello there! 

I am tryning to run musika on linux. I followed all the steps, but running the line to install the requirements I get this: 

...
Collecting websockets (from gradio==3.3.1->-r requirements.txt (line 4))
  Using cached websockets-3.3-py33.py34.py35.py36-none-any.whl (38 kB)
Collecting uvicorn (from gradio==3.3.1->-r requirements.txt (line 4))
  Using cached uvicorn-0.2.1.tar.gz (10 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-7c3apuja/uvicorn_8f06a81bddcc4ab5a01e4d33c81577b9/setup.py", line 41, in <module>
          long_description=get_long_description(),
        File "/tmp/pip-install-7c3apuja/uvicorn_8f06a81bddcc4ab5a01e4d33c81577b9/setup.py", line 23, in get_long_description
          return open('README.md', 'r').read()
      FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
(musika) zaib@zaib:~/musika$ 

I read on another github page I found casually trying to figure the error out, that it might be a problem with uvicorn-0.2.1.tar.gz, that version of uvicorn is indeed a little old, but taking a look at the libraries in the requirements.txt, uvicorn is not explicitly mentioned, therefore it is not possible to modify the version directly. 
Is there any solution to that? 
Many thanks

**Comment by marcoppasini** [comment]
Hello!
I have just tried installing the requirements in the Colab notebook I provided (https://colab.research.google.com/drive/1PowSw3doBURwLE-OTCiWkO8HVbS5paRb) and everything is installed without any issue.
Can you maybe try again using a new clean environment?

**Comment by dr-zaib** [comment]
Hello! 
Thanks for replying!
I have solved it by adding the uvicorn library (without precising any version of it) to the requirements right before the gradio library.
I will also have a look at your solution as well!
ps. your work is great, congratulations!
