### ISSUE TITLE
Setup in Google Colab dont working

### ISSUE THREAD

**Issue by lol55675** [marcoppasini/musika#41]
When i run setup cell in Google Colab it runs very slowly and setup never finished.
And print: INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking

**Comment by samiy803** [comment]
I got it working by using pip's old dependency resolver: 
```
!pip install -r requirements.txt --use-deprecated=legacy-resolver
```

**Comment by lol55675** [comment]
I got all things working but now when i run finetune cell it gives error:


Using CPU...

Calculating total number of samples in data folder...
Found 153 total samples
Dataset is ready!
Checking if models are already available...
Models are available!
/usr/local/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer HeUniform is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
Traceback (most recent call last):
  File "/content/musika/musika_train.py", line 23, in <module>
    models_ls = M.initialize_networks()
  File "/content/musika/models.py", line 760, in initialize_networks
    (critic, gen, enc, dec, enc2, dec2, gen_ema, [opt_dec, opt_disc], switch) = self.get_networks()
  File "/content/musika/models.py", line 739, in get_networks
    ) = self.load(self.args.load_path, load_dec=False)
  File "/content/musika/models.py", line 669, in load
    opt_disc.set_weights(np.load(path + "/opt_disc.npy", allow_pickle=True))
  File "/usr/local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 407, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/content/musika/checkpoints/misc/opt_disc.npy'
